/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProRouteImport } from './routes/pro'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InfRouteImport } from './routes/inf'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProIndexRouteImport } from './routes/pro.index'
import { Route as InfIndexRouteImport } from './routes/inf.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as ProTreinosRouteImport } from './routes/pro.treinos'
import { Route as ProNotificacoesRouteImport } from './routes/pro.notificacoes'
import { Route as ProFinanceiroRouteImport } from './routes/pro.financeiro'
import { Route as ProContratosRouteImport } from './routes/pro.contratos'
import { Route as ProAlunosRouteImport } from './routes/pro.alunos'
import { Route as InfLinkRouteImport } from './routes/inf.link'
import { Route as InfIndicacoesRouteImport } from './routes/inf.indicacoes'
import { Route as InfFinanceiroRouteImport } from './routes/inf.financeiro'
import { Route as AppTreinosRouteImport } from './routes/app.treinos'
import { Route as AppScoreRouteImport } from './routes/app.score'
import { Route as AppRankingsRouteImport } from './routes/app.rankings'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppNotificacoesRouteImport } from './routes/app.notificacoes'
import { Route as AppEvolucaoRouteImport } from './routes/app.evolucao'
import { Route as AppDesafiosRouteImport } from './routes/app.desafios'
import { Route as AppComunidadeRouteImport } from './routes/app.comunidade'
import { Route as AppAssinaturaRouteImport } from './routes/app.assinatura'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminNotificacoesRouteImport } from './routes/admin.notificacoes'
import { Route as AdminInfluenciadoresRouteImport } from './routes/admin.influenciadores'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminConteudoRouteImport } from './routes/admin.conteudo'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AppRunIndexRouteImport } from './routes/app.run.index'
import { Route as ProAlunosIdRouteImport } from './routes/pro.alunos.$id'
import { Route as AppTreinosIdRouteImport } from './routes/app.treinos.$id'
import { Route as AppRunIniciarRouteImport } from './routes/app.run.iniciar'

const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InfRoute = InfRouteImport.update({
  id: '/inf',
  path: '/inf',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProIndexRoute = ProIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProRoute,
} as any)
const InfIndexRoute = InfIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InfRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ProTreinosRoute = ProTreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => ProRoute,
} as any)
const ProNotificacoesRoute = ProNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => ProRoute,
} as any)
const ProFinanceiroRoute = ProFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => ProRoute,
} as any)
const ProContratosRoute = ProContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => ProRoute,
} as any)
const ProAlunosRoute = ProAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => ProRoute,
} as any)
const InfLinkRoute = InfLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => InfRoute,
} as any)
const InfIndicacoesRoute = InfIndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => InfRoute,
} as any)
const InfFinanceiroRoute = InfFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => InfRoute,
} as any)
const AppTreinosRoute = AppTreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => AppRoute,
} as any)
const AppScoreRoute = AppScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingsRoute = AppRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppEvolucaoRoute = AppEvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => AppRoute,
} as any)
const AppDesafiosRoute = AppDesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => AppRoute,
} as any)
const AppComunidadeRoute = AppComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => AppRoute,
} as any)
const AppAssinaturaRoute = AppAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificacoesRoute = AdminNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInfluenciadoresRoute = AdminInfluenciadoresRouteImport.update({
  id: '/influenciadores',
  path: '/influenciadores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudoRoute = AdminConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AppRunIndexRoute = AppRunIndexRouteImport.update({
  id: '/run/',
  path: '/run/',
  getParentRoute: () => AppRoute,
} as any)
const ProAlunosIdRoute = ProAlunosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProAlunosRoute,
} as any)
const AppTreinosIdRoute = AppTreinosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTreinosRoute,
} as any)
const AppRunIniciarRoute = AppRunIniciarRouteImport.update({
  id: '/run/iniciar',
  path: '/run/iniciar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/inf': typeof InfRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pro': typeof ProRouteWithChildren
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/influenciadores': typeof AdminInfluenciadoresRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/comunidade': typeof AppComunidadeRoute
  '/app/desafios': typeof AppDesafiosRoute
  '/app/evolucao': typeof AppEvolucaoRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/rankings': typeof AppRankingsRoute
  '/app/score': typeof AppScoreRoute
  '/app/treinos': typeof AppTreinosRouteWithChildren
  '/inf/financeiro': typeof InfFinanceiroRoute
  '/inf/indicacoes': typeof InfIndicacoesRoute
  '/inf/link': typeof InfLinkRoute
  '/pro/alunos': typeof ProAlunosRouteWithChildren
  '/pro/contratos': typeof ProContratosRoute
  '/pro/financeiro': typeof ProFinanceiroRoute
  '/pro/notificacoes': typeof ProNotificacoesRoute
  '/pro/treinos': typeof ProTreinosRoute
  '/r/$code': typeof RCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/inf/': typeof InfIndexRoute
  '/pro/': typeof ProIndexRoute
  '/app/run/iniciar': typeof AppRunIniciarRoute
  '/app/treinos/$id': typeof AppTreinosIdRoute
  '/pro/alunos/$id': typeof ProAlunosIdRoute
  '/app/run/': typeof AppRunIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/influenciadores': typeof AdminInfluenciadoresRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/comunidade': typeof AppComunidadeRoute
  '/app/desafios': typeof AppDesafiosRoute
  '/app/evolucao': typeof AppEvolucaoRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/rankings': typeof AppRankingsRoute
  '/app/score': typeof AppScoreRoute
  '/app/treinos': typeof AppTreinosRouteWithChildren
  '/inf/financeiro': typeof InfFinanceiroRoute
  '/inf/indicacoes': typeof InfIndicacoesRoute
  '/inf/link': typeof InfLinkRoute
  '/pro/alunos': typeof ProAlunosRouteWithChildren
  '/pro/contratos': typeof ProContratosRoute
  '/pro/financeiro': typeof ProFinanceiroRoute
  '/pro/notificacoes': typeof ProNotificacoesRoute
  '/pro/treinos': typeof ProTreinosRoute
  '/r/$code': typeof RCodeRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/inf': typeof InfIndexRoute
  '/pro': typeof ProIndexRoute
  '/app/run/iniciar': typeof AppRunIniciarRoute
  '/app/treinos/$id': typeof AppTreinosIdRoute
  '/pro/alunos/$id': typeof ProAlunosIdRoute
  '/app/run': typeof AppRunIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/inf': typeof InfRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pro': typeof ProRouteWithChildren
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/influenciadores': typeof AdminInfluenciadoresRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/comunidade': typeof AppComunidadeRoute
  '/app/desafios': typeof AppDesafiosRoute
  '/app/evolucao': typeof AppEvolucaoRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/rankings': typeof AppRankingsRoute
  '/app/score': typeof AppScoreRoute
  '/app/treinos': typeof AppTreinosRouteWithChildren
  '/inf/financeiro': typeof InfFinanceiroRoute
  '/inf/indicacoes': typeof InfIndicacoesRoute
  '/inf/link': typeof InfLinkRoute
  '/pro/alunos': typeof ProAlunosRouteWithChildren
  '/pro/contratos': typeof ProContratosRoute
  '/pro/financeiro': typeof ProFinanceiroRoute
  '/pro/notificacoes': typeof ProNotificacoesRoute
  '/pro/treinos': typeof ProTreinosRoute
  '/r/$code': typeof RCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/inf/': typeof InfIndexRoute
  '/pro/': typeof ProIndexRoute
  '/app/run/iniciar': typeof AppRunIniciarRoute
  '/app/treinos/$id': typeof AppTreinosIdRoute
  '/pro/alunos/$id': typeof ProAlunosIdRoute
  '/app/run/': typeof AppRunIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/cadastro'
    | '/inf'
    | '/login'
    | '/onboarding'
    | '/pro'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/financeiro'
    | '/admin/influenciadores'
    | '/admin/notificacoes'
    | '/admin/usuarios'
    | '/app/assinatura'
    | '/app/comunidade'
    | '/app/desafios'
    | '/app/evolucao'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/rankings'
    | '/app/score'
    | '/app/treinos'
    | '/inf/financeiro'
    | '/inf/indicacoes'
    | '/inf/link'
    | '/pro/alunos'
    | '/pro/contratos'
    | '/pro/financeiro'
    | '/pro/notificacoes'
    | '/pro/treinos'
    | '/r/$code'
    | '/admin/'
    | '/app/'
    | '/inf/'
    | '/pro/'
    | '/app/run/iniciar'
    | '/app/treinos/$id'
    | '/pro/alunos/$id'
    | '/app/run/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/onboarding'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/financeiro'
    | '/admin/influenciadores'
    | '/admin/notificacoes'
    | '/admin/usuarios'
    | '/app/assinatura'
    | '/app/comunidade'
    | '/app/desafios'
    | '/app/evolucao'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/rankings'
    | '/app/score'
    | '/app/treinos'
    | '/inf/financeiro'
    | '/inf/indicacoes'
    | '/inf/link'
    | '/pro/alunos'
    | '/pro/contratos'
    | '/pro/financeiro'
    | '/pro/notificacoes'
    | '/pro/treinos'
    | '/r/$code'
    | '/admin'
    | '/app'
    | '/inf'
    | '/pro'
    | '/app/run/iniciar'
    | '/app/treinos/$id'
    | '/pro/alunos/$id'
    | '/app/run'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/cadastro'
    | '/inf'
    | '/login'
    | '/onboarding'
    | '/pro'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/financeiro'
    | '/admin/influenciadores'
    | '/admin/notificacoes'
    | '/admin/usuarios'
    | '/app/assinatura'
    | '/app/comunidade'
    | '/app/desafios'
    | '/app/evolucao'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/rankings'
    | '/app/score'
    | '/app/treinos'
    | '/inf/financeiro'
    | '/inf/indicacoes'
    | '/inf/link'
    | '/pro/alunos'
    | '/pro/contratos'
    | '/pro/financeiro'
    | '/pro/notificacoes'
    | '/pro/treinos'
    | '/r/$code'
    | '/admin/'
    | '/app/'
    | '/inf/'
    | '/pro/'
    | '/app/run/iniciar'
    | '/app/treinos/$id'
    | '/pro/alunos/$id'
    | '/app/run/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  InfRoute: typeof InfRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProRoute: typeof ProRouteWithChildren
  RCodeRoute: typeof RCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inf': {
      id: '/inf'
      path: '/inf'
      fullPath: '/inf'
      preLoaderRoute: typeof InfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/': {
      id: '/pro/'
      path: '/'
      fullPath: '/pro/'
      preLoaderRoute: typeof ProIndexRouteImport
      parentRoute: typeof ProRoute
    }
    '/inf/': {
      id: '/inf/'
      path: '/'
      fullPath: '/inf/'
      preLoaderRoute: typeof InfIndexRouteImport
      parentRoute: typeof InfRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/treinos': {
      id: '/pro/treinos'
      path: '/treinos'
      fullPath: '/pro/treinos'
      preLoaderRoute: typeof ProTreinosRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/notificacoes': {
      id: '/pro/notificacoes'
      path: '/notificacoes'
      fullPath: '/pro/notificacoes'
      preLoaderRoute: typeof ProNotificacoesRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/financeiro': {
      id: '/pro/financeiro'
      path: '/financeiro'
      fullPath: '/pro/financeiro'
      preLoaderRoute: typeof ProFinanceiroRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/contratos': {
      id: '/pro/contratos'
      path: '/contratos'
      fullPath: '/pro/contratos'
      preLoaderRoute: typeof ProContratosRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/alunos': {
      id: '/pro/alunos'
      path: '/alunos'
      fullPath: '/pro/alunos'
      preLoaderRoute: typeof ProAlunosRouteImport
      parentRoute: typeof ProRoute
    }
    '/inf/link': {
      id: '/inf/link'
      path: '/link'
      fullPath: '/inf/link'
      preLoaderRoute: typeof InfLinkRouteImport
      parentRoute: typeof InfRoute
    }
    '/inf/indicacoes': {
      id: '/inf/indicacoes'
      path: '/indicacoes'
      fullPath: '/inf/indicacoes'
      preLoaderRoute: typeof InfIndicacoesRouteImport
      parentRoute: typeof InfRoute
    }
    '/inf/financeiro': {
      id: '/inf/financeiro'
      path: '/financeiro'
      fullPath: '/inf/financeiro'
      preLoaderRoute: typeof InfFinanceiroRouteImport
      parentRoute: typeof InfRoute
    }
    '/app/treinos': {
      id: '/app/treinos'
      path: '/treinos'
      fullPath: '/app/treinos'
      preLoaderRoute: typeof AppTreinosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/score': {
      id: '/app/score'
      path: '/score'
      fullPath: '/app/score'
      preLoaderRoute: typeof AppScoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rankings': {
      id: '/app/rankings'
      path: '/rankings'
      fullPath: '/app/rankings'
      preLoaderRoute: typeof AppRankingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notificacoes': {
      id: '/app/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evolucao': {
      id: '/app/evolucao'
      path: '/evolucao'
      fullPath: '/app/evolucao'
      preLoaderRoute: typeof AppEvolucaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/desafios': {
      id: '/app/desafios'
      path: '/desafios'
      fullPath: '/app/desafios'
      preLoaderRoute: typeof AppDesafiosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comunidade': {
      id: '/app/comunidade'
      path: '/comunidade'
      fullPath: '/app/comunidade'
      preLoaderRoute: typeof AppComunidadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assinatura': {
      id: '/app/assinatura'
      path: '/assinatura'
      fullPath: '/app/assinatura'
      preLoaderRoute: typeof AppAssinaturaRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notificacoes': {
      id: '/admin/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AdminNotificacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/influenciadores': {
      id: '/admin/influenciadores'
      path: '/influenciadores'
      fullPath: '/admin/influenciadores'
      preLoaderRoute: typeof AdminInfluenciadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo': {
      id: '/admin/conteudo'
      path: '/conteudo'
      fullPath: '/admin/conteudo'
      preLoaderRoute: typeof AdminConteudoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/run/': {
      id: '/app/run/'
      path: '/run'
      fullPath: '/app/run/'
      preLoaderRoute: typeof AppRunIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/pro/alunos/$id': {
      id: '/pro/alunos/$id'
      path: '/$id'
      fullPath: '/pro/alunos/$id'
      preLoaderRoute: typeof ProAlunosIdRouteImport
      parentRoute: typeof ProAlunosRoute
    }
    '/app/treinos/$id': {
      id: '/app/treinos/$id'
      path: '/$id'
      fullPath: '/app/treinos/$id'
      preLoaderRoute: typeof AppTreinosIdRouteImport
      parentRoute: typeof AppTreinosRoute
    }
    '/app/run/iniciar': {
      id: '/app/run/iniciar'
      path: '/run/iniciar'
      fullPath: '/app/run/iniciar'
      preLoaderRoute: typeof AppRunIniciarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminConteudoRoute: typeof AdminConteudoRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminInfluenciadoresRoute: typeof AdminInfluenciadoresRoute
  AdminNotificacoesRoute: typeof AdminNotificacoesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminConteudoRoute: AdminConteudoRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminInfluenciadoresRoute: AdminInfluenciadoresRoute,
  AdminNotificacoesRoute: AdminNotificacoesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppTreinosRouteChildren {
  AppTreinosIdRoute: typeof AppTreinosIdRoute
}

const AppTreinosRouteChildren: AppTreinosRouteChildren = {
  AppTreinosIdRoute: AppTreinosIdRoute,
}

const AppTreinosRouteWithChildren = AppTreinosRoute._addFileChildren(
  AppTreinosRouteChildren,
)

interface AppRouteChildren {
  AppAssinaturaRoute: typeof AppAssinaturaRoute
  AppComunidadeRoute: typeof AppComunidadeRoute
  AppDesafiosRoute: typeof AppDesafiosRoute
  AppEvolucaoRoute: typeof AppEvolucaoRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRankingsRoute: typeof AppRankingsRoute
  AppScoreRoute: typeof AppScoreRoute
  AppTreinosRoute: typeof AppTreinosRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppRunIniciarRoute: typeof AppRunIniciarRoute
  AppRunIndexRoute: typeof AppRunIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssinaturaRoute: AppAssinaturaRoute,
  AppComunidadeRoute: AppComunidadeRoute,
  AppDesafiosRoute: AppDesafiosRoute,
  AppEvolucaoRoute: AppEvolucaoRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRankingsRoute: AppRankingsRoute,
  AppScoreRoute: AppScoreRoute,
  AppTreinosRoute: AppTreinosRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppRunIniciarRoute: AppRunIniciarRoute,
  AppRunIndexRoute: AppRunIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface InfRouteChildren {
  InfFinanceiroRoute: typeof InfFinanceiroRoute
  InfIndicacoesRoute: typeof InfIndicacoesRoute
  InfLinkRoute: typeof InfLinkRoute
  InfIndexRoute: typeof InfIndexRoute
}

const InfRouteChildren: InfRouteChildren = {
  InfFinanceiroRoute: InfFinanceiroRoute,
  InfIndicacoesRoute: InfIndicacoesRoute,
  InfLinkRoute: InfLinkRoute,
  InfIndexRoute: InfIndexRoute,
}

const InfRouteWithChildren = InfRoute._addFileChildren(InfRouteChildren)

interface ProAlunosRouteChildren {
  ProAlunosIdRoute: typeof ProAlunosIdRoute
}

const ProAlunosRouteChildren: ProAlunosRouteChildren = {
  ProAlunosIdRoute: ProAlunosIdRoute,
}

const ProAlunosRouteWithChildren = ProAlunosRoute._addFileChildren(
  ProAlunosRouteChildren,
)

interface ProRouteChildren {
  ProAlunosRoute: typeof ProAlunosRouteWithChildren
  ProContratosRoute: typeof ProContratosRoute
  ProFinanceiroRoute: typeof ProFinanceiroRoute
  ProNotificacoesRoute: typeof ProNotificacoesRoute
  ProTreinosRoute: typeof ProTreinosRoute
  ProIndexRoute: typeof ProIndexRoute
}

const ProRouteChildren: ProRouteChildren = {
  ProAlunosRoute: ProAlunosRouteWithChildren,
  ProContratosRoute: ProContratosRoute,
  ProFinanceiroRoute: ProFinanceiroRoute,
  ProNotificacoesRoute: ProNotificacoesRoute,
  ProTreinosRoute: ProTreinosRoute,
  ProIndexRoute: ProIndexRoute,
}

const ProRouteWithChildren = ProRoute._addFileChildren(ProRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  InfRoute: InfRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProRoute: ProRouteWithChildren,
  RCodeRoute: RCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
