/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTreinosRouteImport } from './routes/app.treinos'
import { Route as AppScoreRouteImport } from './routes/app.score'
import { Route as AppRankingsRouteImport } from './routes/app.rankings'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppNotificacoesRouteImport } from './routes/app.notificacoes'
import { Route as AppEvolucaoRouteImport } from './routes/app.evolucao'
import { Route as AppDesafiosRouteImport } from './routes/app.desafios'
import { Route as AppComunidadeRouteImport } from './routes/app.comunidade'
import { Route as AppAssinaturaRouteImport } from './routes/app.assinatura'
import { Route as AppRunIndexRouteImport } from './routes/app.run.index'
import { Route as AppTreinosIdRouteImport } from './routes/app.treinos.$id'
import { Route as AppRunIniciarRouteImport } from './routes/app.run.iniciar'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTreinosRoute = AppTreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => AppRoute,
} as any)
const AppScoreRoute = AppScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingsRoute = AppRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppEvolucaoRoute = AppEvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => AppRoute,
} as any)
const AppDesafiosRoute = AppDesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => AppRoute,
} as any)
const AppComunidadeRoute = AppComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => AppRoute,
} as any)
const AppAssinaturaRoute = AppAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AppRoute,
} as any)
const AppRunIndexRoute = AppRunIndexRouteImport.update({
  id: '/run/',
  path: '/run/',
  getParentRoute: () => AppRoute,
} as any)
const AppTreinosIdRoute = AppTreinosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTreinosRoute,
} as any)
const AppRunIniciarRoute = AppRunIniciarRouteImport.update({
  id: '/run/iniciar',
  path: '/run/iniciar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/comunidade': typeof AppComunidadeRoute
  '/app/desafios': typeof AppDesafiosRoute
  '/app/evolucao': typeof AppEvolucaoRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/rankings': typeof AppRankingsRoute
  '/app/score': typeof AppScoreRoute
  '/app/treinos': typeof AppTreinosRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/run/iniciar': typeof AppRunIniciarRoute
  '/app/treinos/$id': typeof AppTreinosIdRoute
  '/app/run/': typeof AppRunIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/comunidade': typeof AppComunidadeRoute
  '/app/desafios': typeof AppDesafiosRoute
  '/app/evolucao': typeof AppEvolucaoRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/rankings': typeof AppRankingsRoute
  '/app/score': typeof AppScoreRoute
  '/app/treinos': typeof AppTreinosRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/run/iniciar': typeof AppRunIniciarRoute
  '/app/treinos/$id': typeof AppTreinosIdRoute
  '/app/run': typeof AppRunIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/comunidade': typeof AppComunidadeRoute
  '/app/desafios': typeof AppDesafiosRoute
  '/app/evolucao': typeof AppEvolucaoRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/rankings': typeof AppRankingsRoute
  '/app/score': typeof AppScoreRoute
  '/app/treinos': typeof AppTreinosRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/run/iniciar': typeof AppRunIniciarRoute
  '/app/treinos/$id': typeof AppTreinosIdRoute
  '/app/run/': typeof AppRunIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/onboarding'
    | '/app/assinatura'
    | '/app/comunidade'
    | '/app/desafios'
    | '/app/evolucao'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/rankings'
    | '/app/score'
    | '/app/treinos'
    | '/app/'
    | '/app/run/iniciar'
    | '/app/treinos/$id'
    | '/app/run/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/onboarding'
    | '/app/assinatura'
    | '/app/comunidade'
    | '/app/desafios'
    | '/app/evolucao'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/rankings'
    | '/app/score'
    | '/app/treinos'
    | '/app'
    | '/app/run/iniciar'
    | '/app/treinos/$id'
    | '/app/run'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/onboarding'
    | '/app/assinatura'
    | '/app/comunidade'
    | '/app/desafios'
    | '/app/evolucao'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/rankings'
    | '/app/score'
    | '/app/treinos'
    | '/app/'
    | '/app/run/iniciar'
    | '/app/treinos/$id'
    | '/app/run/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/treinos': {
      id: '/app/treinos'
      path: '/treinos'
      fullPath: '/app/treinos'
      preLoaderRoute: typeof AppTreinosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/score': {
      id: '/app/score'
      path: '/score'
      fullPath: '/app/score'
      preLoaderRoute: typeof AppScoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rankings': {
      id: '/app/rankings'
      path: '/rankings'
      fullPath: '/app/rankings'
      preLoaderRoute: typeof AppRankingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notificacoes': {
      id: '/app/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evolucao': {
      id: '/app/evolucao'
      path: '/evolucao'
      fullPath: '/app/evolucao'
      preLoaderRoute: typeof AppEvolucaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/desafios': {
      id: '/app/desafios'
      path: '/desafios'
      fullPath: '/app/desafios'
      preLoaderRoute: typeof AppDesafiosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comunidade': {
      id: '/app/comunidade'
      path: '/comunidade'
      fullPath: '/app/comunidade'
      preLoaderRoute: typeof AppComunidadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assinatura': {
      id: '/app/assinatura'
      path: '/assinatura'
      fullPath: '/app/assinatura'
      preLoaderRoute: typeof AppAssinaturaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/run/': {
      id: '/app/run/'
      path: '/run'
      fullPath: '/app/run/'
      preLoaderRoute: typeof AppRunIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/treinos/$id': {
      id: '/app/treinos/$id'
      path: '/$id'
      fullPath: '/app/treinos/$id'
      preLoaderRoute: typeof AppTreinosIdRouteImport
      parentRoute: typeof AppTreinosRoute
    }
    '/app/run/iniciar': {
      id: '/app/run/iniciar'
      path: '/run/iniciar'
      fullPath: '/app/run/iniciar'
      preLoaderRoute: typeof AppRunIniciarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppTreinosRouteChildren {
  AppTreinosIdRoute: typeof AppTreinosIdRoute
}

const AppTreinosRouteChildren: AppTreinosRouteChildren = {
  AppTreinosIdRoute: AppTreinosIdRoute,
}

const AppTreinosRouteWithChildren = AppTreinosRoute._addFileChildren(
  AppTreinosRouteChildren,
)

interface AppRouteChildren {
  AppAssinaturaRoute: typeof AppAssinaturaRoute
  AppComunidadeRoute: typeof AppComunidadeRoute
  AppDesafiosRoute: typeof AppDesafiosRoute
  AppEvolucaoRoute: typeof AppEvolucaoRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRankingsRoute: typeof AppRankingsRoute
  AppScoreRoute: typeof AppScoreRoute
  AppTreinosRoute: typeof AppTreinosRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppRunIniciarRoute: typeof AppRunIniciarRoute
  AppRunIndexRoute: typeof AppRunIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssinaturaRoute: AppAssinaturaRoute,
  AppComunidadeRoute: AppComunidadeRoute,
  AppDesafiosRoute: AppDesafiosRoute,
  AppEvolucaoRoute: AppEvolucaoRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRankingsRoute: AppRankingsRoute,
  AppScoreRoute: AppScoreRoute,
  AppTreinosRoute: AppTreinosRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppRunIniciarRoute: AppRunIniciarRoute,
  AppRunIndexRoute: AppRunIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
